version: "3.7"

services:
  db:
    image: postgres:13
    container_name: db4${PROJECT_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5435:5432
    volumes:
      - pgdata:/data/postgres
    env_file:
      - .env

  app:
    build: .
    container_name: app4${PROJECT_NAME}
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local